---
- hosts: fonos
  vars:
  - fonos_path: /home/pi/fonos
  - python_major_minor: "{{'.'.join(ansible_python_version.split('.')[:2])}}"
  remote_user: pi
  tasks:
  - name: add mopidy repository key
    become: yes
    apt_key:
      url: https://apt.mopidy.com/mopidy.gpg
  - name: use mopidy sources list (for libspotify)
    become: yes
    apt_repository:
      repo: deb http://apt.mopidy.com/ {{ansible_distribution_release}} main contrib non-free
  - name: install deb packages
    become: yes
    apt:
      state: present
      update_cache: yes
      name:
      - build-essential
      - python3-dev
      - python3-virtualenv
      - python3-gst-1.0
      - git
      - pulseaudio
      - pulseaudio-module-bluetooth
      - pulseaudio-module-zeroconf
      - gstreamer1.0-tools
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-pulseaudio
      - gir1.2-gstreamer-1.0
      - gir1.2-gst-plugins-base-1.0
      - libffi-dev
      - libspotify-dev
      - php-cli
  - name: make sure that our "root" directory exists
    file:
      path: "{{fonos_path}}"
      state: directory
  - name: copy requirements.txt
    copy: src=./requirements.txt dest={{fonos_path}}/requirements.txt
  - name: setup virtualenv
    pip:
      requirements: "{{fonos_path}}/requirements.txt"
      virtualenv: "{{fonos_path}}/env"
  - name: setup symlink for gstreamer/gobject/python in virtualenv
    file:
      state: link
      src: /usr/lib/python3/dist-packages/gi
      dest: "{{fonos_path}}/env/lib/python{{python_major_minor}}/site-packages/gi"
  - name: checkout PaWebControl
    git:
      repo: git://github.com/jpetazzo/PaWebControl
      dest: "{{fonos_path}}/PaWebControl"
  - name: checkout AuRevoir
    git:
      repo: git://github.com/jpetazzo/AuRevoir
      dest: "{{fonos_path}}/AuRevoir"
  - name: create Mopidy config directory
    file:
      path: "{{ansible_env.HOME}}/.config/mopidy"
      state: directory
  - name: generate Mopidy configuration
    template:
      src: ./mopidy.conf.j2
      dest: "{{ansible_env.HOME}}/.config/mopidy/mopidy.conf"
  - name: create PulseAudio config directory
    file:
      path: "{{ansible_env.HOME}}/.config/pulse"
      state: directory
  - name: copy PulseAudio configuration
    with_items:
    - client.conf
    - daemon.conf
    - default.pa
    copy:
      src: ./pulse-{{item}}
      dest: "{{ansible_env.HOME}}/.config/pulse/{{item}}"
  - name: create systemd config directory
    file:
      path: "{{ansible_env.HOME}}/.config/systemd/user"
      state: directory
  - name: automatically start systemd units for our user
    become: yes
    command: loginctl enable-linger {{ansible_user_id}}
  - name: create systemd units directory
    file:
      path: "{{ansible_env.HOME}}/.config/systemd/user"
      state: directory
  - name: copy systemd units
    with_items:
    - aurevoir
    - mopidy
    - pawebcontrol
    - pulseaudio
    copy:
      src: ./systemd/user/{{item}}.service
      dest: "{{ansible_env.HOME}}/.config/systemd/user/{{item}}.service"
  - name: enable systemd units
    with_items:
    - aurevoir
    - mopidy
    - pawebcontrol
    - pulseaudio
    systemd:
      daemon_reload: yes
      enabled: yes
      name: "{{item}}"
      state: restarted
      scope: user